[project]
name = "nicegui-zeitline"
version = "0.1.0"
description = "NiceGUI wrapper around ZeitlineJS timeline component."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "nicegui>=2.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
